name: Deployment Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Testing VPS connection and deploy project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          port: ${{ secrets.PORT}}
          username: ${{ secrets.USERNAME}}
          key: ${{ secrets.PRIVATE_KEY}}
          script: |
            cd /home/kentforth/webapps/Control-Surface
            git pull
            yarn install --production
            yarn add @vue/cli-service
            yarn build
            sudo systemctl restart nginx
