name: Deployment Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Testing VPS connection and deploy project
        uses: appleboy/ssh-action@master
        with:
          host: 46.229.214.53
          port: 4040
          username: kentforth
          key: ${{ secrets.PRIVATE_KEY}}
          uses: appleboy/ssh-action@master
          script: |
            cd /home/kentforth/webapps/Control-Surface
            git pull
            yarn install --production
            yarn build

